@startuml colaboration-open
!theme plain

actor player

package angular {
    agent startViewHTML
    agent startViewComponent
    agent startService
    agent httpClient
}

player -right-> startViewHTML :open(gameName)
startViewHTML --> startViewComponent :open(gameName)
startViewComponent --> startService :open(gameName)
startService --> httpClient :get(gameName)

package controllers <<master-mind-core dependency>> {
    agent startController
}

httpClient -left-> startController :get(gameName)

package dao {
    agent sessionImpDAO
    agent gameDAO
    agent propCombDAO
    agent gameDTO
}

package models <<master-mind-core dependency>>{
    agent session
    agent sessionDTO
    agent game
}

startController --> session :next()
startController --> sessionImpDAO :load(gameSelectedTitle)\nassociate(this.session)
sessionImpDAO --> gameDAO :getGame()
sessionImpDAO --> propCombDAO :getPropCombs()
sessionImpDAO --> sessionDTO :load(game)
sessionImpDAO --> gameDTO :getLoad(game)


sessionDTO -right-> session :load(game) 
sessionDTO ..> game 
gameDTO -right-> game :new()

@enduml